[package]
name = "SurrealDB-learnings"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
surrealdb = "1.5.2"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread", "full"] }
warp = "0.3"